version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - ### aws ecr get-login-password 

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t yt-video-image .
      - ### docker tag 


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push ### 
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "" "" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
